//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooville.QUno.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mooville.QUno.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About QUno.
        /// </summary>
        internal static string CommandAbout {
            get {
                return ResourceManager.GetString("CommandAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        internal static string CommandAddPlayer {
            get {
                return ResourceManager.GetString("CommandAddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CommandCheckForUpdates {
            get {
                return ResourceManager.GetString("CommandCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Card.
        /// </summary>
        internal static string CommandDrawCard {
            get {
                return ResourceManager.GetString("CommandDrawCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Update.
        /// </summary>
        internal static string CommandGetUpdate {
            get {
                return ResourceManager.GetString("CommandGetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string CommandOptions {
            get {
                return ResourceManager.GetString("CommandOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Card.
        /// </summary>
        internal static string CommandPlayCard {
            get {
                return ResourceManager.GetString("CommandPlayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Player.
        /// </summary>
        internal static string CommandRemovePlayer {
            get {
                return ResourceManager.GetString("CommandRemovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string CommandStartGame {
            get {
                return ResourceManager.GetString("CommandStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Turn.
        /// </summary>
        internal static string CommandTakeTurn {
            get {
                return ResourceManager.GetString("CommandTakeTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUno Files|*.quno|All Files|*.*.
        /// </summary>
        internal static string FilterQUnoFiles {
            get {
                return ResourceManager.GetString("FilterQUnoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} drew a card.
        /// </summary>
        internal static string LogMessageDraw {
            get {
                return ResourceManager.GetString("LogMessageDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} played {1}.
        /// </summary>
        internal static string LogMessagePlay {
            get {
                return ResourceManager.GetString("LogMessagePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} played {1} and chose {2}.
        /// </summary>
        internal static string LogMessageWildPlay {
            get {
                return ResourceManager.GetString("LogMessageWildPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Get Update to learn more..
        /// </summary>
        internal static string MessageCheckForUpdatesUpdateAvailable {
            get {
                return ResourceManager.GetString("MessageCheckForUpdatesUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}.
        /// </summary>
        internal static string PlayerNameTemplate {
            get {
                return ResourceManager.GetString("PlayerNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusDefault {
            get {
                return ResourceManager.GetString("StatusDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game in progress.
        /// </summary>
        internal static string StatusGameInProgress {
            get {
                return ResourceManager.GetString("StatusGameInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over! {0} is the winner..
        /// </summary>
        internal static string StatusGameOver {
            get {
                return ResourceManager.GetString("StatusGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates was cancelled.
        /// </summary>
        internal static string TitleCheckForUpdatesCancelled {
            get {
                return ResourceManager.GetString("TitleCheckForUpdatesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem checking for updates.
        /// </summary>
        internal static string TitleCheckForUpdatesError {
            get {
                return ResourceManager.GetString("TitleCheckForUpdatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update is available.
        /// </summary>
        internal static string TitleCheckForUpdatesNoUpdateAvailable {
            get {
                return ResourceManager.GetString("TitleCheckForUpdatesNoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        internal static string TitleCheckForUpdatesUpdateAvailable {
            get {
                return ResourceManager.GetString("TitleCheckForUpdatesUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string TitleCheckForUpdatesWorking {
            get {
                return ResourceManager.GetString("TitleCheckForUpdatesWorking", resourceCulture);
            }
        }
    }
}
